[versions]
javierscGradlePlugins = "0.1.1-SNAPSHOT"
kotlin = "1.5.31"

[libraries]
javiersc-gradlePlugins-changelog = { module = "com.javiersc.gradle-plugins:changelog", version.ref = "javierscGradlePlugins" }
jetbrains-kotlin-kotlinGradlePluginX = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
