name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: AddChangelogItem task
        run: ./gradlew addChangelogItem --renovateCommitTable

      - name: Git diff
        run: git diff

      - uses: EndBug/add-and-commit@v7.4.0
        with:
          default_author: user_info
          author_name: 'Javier Segovia Córdoba'
          author_email: 'javier@segoviacordoba.com'
          committer_name: 'Javier Segovia Córdoba'
          committer_email: 'javier@segoviacordoba.com'
          message: 'Add updated dependencies to `CHANGELOG.md`'

      - name: Stop Gradle daemons
        run: ./gradlew --stop
