name: build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: AddChangelogItem task
        run: |
          git config --local user.email "javier@segoviacordoba.com"
          git config --local user.name "Javier Segovia Córdoba"
          ./gradlew addChangelogItem --renovateCommitTable
          git commit --amend --no-edit

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: '${{ github.event.pull_request.base.ref }}'
          github_token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Stop Gradle daemons
        run: ./gradlew --stop
